name: Buildx

on:
  schedule:
    - cron: 0 */12 * * *
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/buildx.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Buildx and push to dockerhub
    steps:
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: node ./build.js \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache"
      - if: always()
        run: rm -f ${HOME}/.docker/config.json
