name: Buildx

on:
  schedule:
    - cron: 0 */1 * * *
  push:
    branches: [master]
    paths:
      - ".github/workflows/buildx.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Buildx and push to dockerhub
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          npm ci
          node ./build.js \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache"

      - name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery crazymax/diun:latest

      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
